### ISSUE TITLE
Cleanup of matrix class

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/DLA-Future#1006]
- rename methods
  - [ ] add new methods
  - [ ] remove old methods
- constructors:
  - [ ] evaluate which methods are needed
  - [ ] evaluate how to improve layout (offset and multiple tiles per block not currently supported)
  - [ ] update tests
- after tridiagonal eigensolver refactoring:
  - [ ] evaluate removal of https://github.com/eth-cscs/DLA-Future/blob/master/include/dlaf/matrix/matrix.h#L35-L48
- [ ] remove `.tpp` files
- [ ] ETI add other types? E.g. `SizeType`
