### ISSUE TITLE
Implement distributed tridiagonal solver.

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/DLA-Future#601]
- [x] #659 @albestro
- [x] final sorting of eigenvectors (@teonnik)
- [x] eigenvector formation (@teonnik)
- [x] #675 givens rotation for deflation (@albestro)

**Comment by rasolca** [comment]
Closed by #719
