### ISSUE TITLE
Tridiagonal eigensolver, reduce gemm complexity taking advantage of the matrix shapes.

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/DLA-Future#917]
The following steps are needed:
- [ ] permute the eigenvectors to have the optimal shape (https://github.com/eth-cscs/DLA-Future/issues/914)
- [ ] Implement the gemm with submatrices and make sure that gemm can be scheduled in a subtask (https://github.com/eth-cscs/DLA-Future/issues/915)
- [ ] Apply the new gemm to the tridiagonal eigensolver (https://github.com/eth-cscs/DLA-Future/issues/916)

Work completed for
- [ ] local implementation
- [ ] distributed implementation
